let mydate = new Date();
console.log(mydate);
console.log(mydate.getFullYear());
console.log(mydate.getMonth());
console.log(mydate.getDay());
console.log(mydate.getDate());
console.log(mydate.getHours());
console.log(mydate.getMinutes());
console.log(mydate.getSeconds());
console.log(mydate.getTime());